--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iZeaoGamer/Discord-bot
build-by-default: true
branches:
- mains
projects:
  Discord-bot:
    path: ""
    includeDirs:
      vendor: vendor
...
