--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iZeaoGamer/Discord-bot#
build-by-default: true
branches:
- main
projects:
  Discord-bot:
    path: ""
    lint:
      phpstan: false
    includeDirs:
      vendor: vendor
...
