name: DiscordBot
version: 2.0.4
author: JaxkDev
main: JaxkDev\DiscordBot\Plugin\Main
description: Plugin to host a discord bot using DiscordPHP with a react\promise API !
website: https://github.com/DiscordBot-PMMP/DiscordBot

api: 3.7.0
extensions:
  core: ">=7.4" #aka PHP Version.

commands:
  debugdiscord:
    permission: op
    description: Debug use only, provides a single file to attach to issues etc helpful when debugging issues.