---
version: 2

discord:
  token: "login token here"
  use_plugin_cacert: true

logging:
  debug: true
  max_files: 28
  directory: "logs"

protocol:
  packets_per_tick: 50
  heartbeat_allowance: 60
...